name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: mkdir ${{runner.workspace}}/build
       
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake -S .. -B . -DCMAKE_BUILD_TYPE=$BUILD_TYPE && pwd

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make -j12
